import sharp from 'sharp'
import { readdir, readFile, unlink, writeFile } from 'fs/promises'
import { existsSync } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const photosDir = path.join(__dirname, '../public/photos')
const srcDir = path.join(__dirname, '../src')
const maxWidth = 800
const quality = 75

async function compressImages() {
  if (!existsSync(photosDir)) {
    console.log('No photos to compress')
    return
  }

  const files = await readdir(photosDir)
  const images = files.filter(f => /\.(jpg|jpeg|png)$/i.test(f))

  console.log(`Compressing ${images.length} images...`)

  for (const file of images) {
    const srcPath = path.join(photosDir, file)
    const webpPath = srcPath.replace(/\.(jpg|jpeg|png)$/i, '.webp')

    try {
      const originalSize = (await readFile(srcPath)).length

      await sharp(srcPath)
        .resize(maxWidth, null, { withoutEnlargement: true })
        .webp({ quality })
        .toFile(webpPath)

      const compressedSize = (await readFile(webpPath)).length
      const saved = ((originalSize - compressedSize) / originalSize * 100).toFixed(1)
      console.log(`✓ ${file} -> ${path.basename(webpPath)} (saved ${saved}%)`)

      // Remove original after successful conversion
      await unlink(srcPath)
    } catch (err) {
      console.error(`✗ Failed to compress ${file}:`, err.message)
    }
  }

  console.log('Compression done! Now generating photos.js...')

  // 生成 photos.js：扫描所有 .webp 文件，获取宽高比
  const allFiles = await readdir(photosDir)
  const webpFiles = allFiles.filter(f => f.endsWith('.webp'))

  const photoData = []
  for (const file of webpFiles) {
    const filePath = path.join(photosDir, file)
    try {
      const metadata = await sharp(filePath).metadata()
      const aspectRatio = metadata.width / metadata.height
      photoData.push({
        name: file,
        aspectRatio: Number(aspectRatio.toFixed(4)),
      })
    } catch (err) {
      console.error(`✗ Failed to read metadata for ${file}:`, err.message)
    }
  }

  // 按文件名排序，保持确定性
  photoData.sort((a, b) => a.name.localeCompare(b.name))

  const jsContent = `// Auto-generated by compress-images.js
// Do not edit manually. Run \`npm run compress\` to regenerate.

export const photos = ${JSON.stringify(photoData, null, 2)}
`

  await writeFile(path.join(srcDir, 'photos.js'), jsContent, 'utf-8')
  console.log(`✓ Generated photos.js with ${photoData.length} photos`)
}

compressImages()
