// Auto-generated by compress-images.js
// Do not edit manually. Run `npm run compress` to regenerate.

export const photos = [
  {
    "name": "000001.webp",
    "aspectRatio": 1.4925
  },
  {
    "name": "000009.webp",
    "aspectRatio": 1.4706
  },
  {
    "name": "000016.webp",
    "aspectRatio": 1.4706
  },
  {
    "name": "000020.webp",
    "aspectRatio": 1.4706
  },
  {
    "name": "000036.webp",
    "aspectRatio": 1.4925
  },
  {
    "name": "000038.webp",
    "aspectRatio": 1.4925
  },
  {
    "name": "000042.webp",
    "aspectRatio": 1.4733
  },
  {
    "name": "000044.webp",
    "aspectRatio": 1.4679
  },
  {
    "name": "000045.webp",
    "aspectRatio": 1.476
  },
  {
    "name": "000053.webp",
    "aspectRatio": 1.476
  },
  {
    "name": "000056.webp",
    "aspectRatio": 1.4953
  },
  {
    "name": "000057.webp",
    "aspectRatio": 1.4925
  },
  {
    "name": "000058.webp",
    "aspectRatio": 1.4953
  },
  {
    "name": "000062.webp",
    "aspectRatio": 1.4925
  },
  {
    "name": "640 (2).webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "IMG_20241205_152207.webp",
    "aspectRatio": 1.3333
  },
  {
    "name": "IMG_20260307_133845.webp",
    "aspectRatio": 0.7498
  },
  {
    "name": "IMG_20260313_220102.webp",
    "aspectRatio": 0.7498
  },
  {
    "name": "IMG_20260416_201806.webp",
    "aspectRatio": 1.3333
  },
  {
    "name": "mmexport1679234225810.webp",
    "aspectRatio": 0.5626
  },
  {
    "name": "mmexport1680182212665.webp",
    "aspectRatio": 1.7778
  },
  {
    "name": "mmexport1680790933092.webp",
    "aspectRatio": 1.7778
  },
  {
    "name": "mmexport1685111276946.webp",
    "aspectRatio": 1.7778
  },
  {
    "name": "mmexport1688976741381.webp",
    "aspectRatio": 0.6667
  },
  {
    "name": "mmexport1701822416188.webp",
    "aspectRatio": 1.7778
  },
  {
    "name": "mmexport1701822424939.webp",
    "aspectRatio": 0.6667
  },
  {
    "name": "mmexport1702634417341.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "mmexport1702634426266.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "mmexport1702642505511.webp",
    "aspectRatio": 0.5626
  },
  {
    "name": "mmexport1702642507687.webp",
    "aspectRatio": 1.7778
  },
  {
    "name": "mmexport1702642511277.webp",
    "aspectRatio": 1.7778
  },
  {
    "name": "mmexport1703256959604.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "mmexport1704553703241.webp",
    "aspectRatio": 1.4981
  },
  {
    "name": "mmexport1704555109967.webp",
    "aspectRatio": 1.6736
  },
  {
    "name": "mmexport1704555113736.webp",
    "aspectRatio": 1.7778
  },
  {
    "name": "mmexport1704555132577.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "mmexport1705671858346.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "mmexport1705672977821.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "mmexport1705754292259.webp",
    "aspectRatio": 1.2841
  },
  {
    "name": "mmexport1705926645847.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "mmexport1711111795495.webp",
    "aspectRatio": 1.8957
  },
  {
    "name": "mmexport1711111797085.webp",
    "aspectRatio": 1.8957
  },
  {
    "name": "mmexport1711111804638.webp",
    "aspectRatio": 1.8957
  },
  {
    "name": "mmexport1711629909033.webp",
    "aspectRatio": 1.8957
  },
  {
    "name": "mmexport1716601939530.webp",
    "aspectRatio": 1.3333
  },
  {
    "name": "mmexport1716652327379.webp",
    "aspectRatio": 1.4109
  },
  {
    "name": "mmexport1722084702979.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "mmexport1722352835947.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "mmexport1722695982644.webp",
    "aspectRatio": 1.7354
  },
  {
    "name": "mmexport1722861247285.webp",
    "aspectRatio": 1.7131
  },
  {
    "name": "mmexport1722953405649.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "mmexport1722953446525.webp",
    "aspectRatio": 0.6667
  },
  {
    "name": "mmexport1722959630483.webp",
    "aspectRatio": 1.8223
  },
  {
    "name": "mmexport1723282156088.webp",
    "aspectRatio": 0.6667
  },
  {
    "name": "mmexport1723308360705.webp",
    "aspectRatio": 0.6667
  },
  {
    "name": "mmexport1723356161971.webp",
    "aspectRatio": 0.6667
  },
  {
    "name": "mmexport1723364674865.webp",
    "aspectRatio": 0.6667
  },
  {
    "name": "mmexport1724599280214.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "mmexport1724681002417.webp",
    "aspectRatio": 1.1696
  },
  {
    "name": "mmexport1726495818089.webp",
    "aspectRatio": 0.6667
  },
  {
    "name": "mmexport1727060916713.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "mmexport1727143618578.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "mmexport1727929401366.webp",
    "aspectRatio": 0.6672
  },
  {
    "name": "mmexport1727929409821.webp",
    "aspectRatio": 0.6672
  },
  {
    "name": "mmexport1728370379636.webp",
    "aspectRatio": 1.4953
  },
  {
    "name": "mmexport1728486606620.webp",
    "aspectRatio": 1.4953
  },
  {
    "name": "mmexport1759133281219.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "mmexport1761533213911.webp",
    "aspectRatio": 1.3333
  },
  {
    "name": "mmexport1762088481413.webp",
    "aspectRatio": 1.3333
  },
  {
    "name": "mmexport1764568730044.webp",
    "aspectRatio": 1.3333
  },
  {
    "name": "mmexport1771082944471.webp",
    "aspectRatio": 0.6667
  },
  {
    "name": "mmexport1772373224267.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "mmexport1772373361887.webp",
    "aspectRatio": 1.7778
  },
  {
    "name": "mmexport1775147268259.webp",
    "aspectRatio": 1.4925
  },
  {
    "name": "mmexport1775147271479.webp",
    "aspectRatio": 1.4925
  },
  {
    "name": "mmexport1775147274245.webp",
    "aspectRatio": 1.4925
  },
  {
    "name": "mmexport1775147280814.webp",
    "aspectRatio": 1.4925
  },
  {
    "name": "momenta-wicv.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "qcraft-autoshow.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "S_R53827.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "SRK5488.webp",
    "aspectRatio": 1.5009
  },
  {
    "name": "YXT_6993.webp",
    "aspectRatio": 1.4981
  },
  {
    "name": "YXT_7011.webp",
    "aspectRatio": 1.4981
  }
]
