import sharp from 'sharp'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// 源目录：通过命令行参数或环境变量指定，默认值为用户的图片目录
const SOURCE_DIR = process.argv[2] || process.env.PHOTOS_SOURCE || 'D:/Web Documents/MY'
const TARGET_DIR = path.join(__dirname, '../public/photos')

const MAX_SIZE = 1024 * 1024 // 1MB

async function compressImage(inputPath, outputPath) {
  const stats = fs.statSync(inputPath)
  const originalSize = stats.size

  if (originalSize <= MAX_SIZE) {
    fs.copyFileSync(inputPath, outputPath)
    return { name: path.basename(outputPath), status: 'skipped', size: originalSize }
  }

  const formats = [
    { ext: 'webp', quality: 85 },
    { ext: 'webp', quality: 75 },
    { ext: 'webp', quality: 70 },
    { ext: 'jpg', quality: 85 },
    { ext: 'jpg', quality: 70 },
  ]

  let bestFile = null
  let bestSize = originalSize
  let bestExt = path.extname(outputPath).toLowerCase()

  for (const fmt of formats) {
    const tempPath = outputPath.replace(/\.[^.]+$/, '.' + fmt.ext)
    try {
      await sharp(inputPath)
        .resize(1920, 1920, { fit: 'inside', withoutEnlargement: true })
        [fmt.ext === 'jpg' ? 'jpeg' : fmt.ext]({ quality: fmt.quality })
        .toFile(tempPath)

      const size = fs.statSync(tempPath).size
      if (size <= MAX_SIZE) {
        // 成功压缩到目标大小，更新最终扩展名
        const finalPath = outputPath.replace(/\.[^.]+$/, '.' + fmt.ext)
        if (tempPath !== finalPath) {
          fs.renameSync(tempPath, finalPath)
        }
        return { name: path.basename(finalPath), status: 'compressed', size }
      }
      if (size < bestSize) {
        bestSize = size
        if (bestFile) fs.unlinkSync(bestFile)
        bestFile = tempPath
        bestExt = '.' + fmt.ext
      } else {
        fs.unlinkSync(tempPath)
      }
    } catch (e) {
      if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath)
    }
  }

  if (bestFile) {
    const finalPath = outputPath.replace(/\.[^.]+$/, bestExt)
    if (bestFile !== finalPath) {
      fs.renameSync(bestFile, finalPath)
    }
    return { name: path.basename(finalPath), status: 'compressed', size: fs.statSync(finalPath).size }
  }

  return { name: path.basename(outputPath), status: 'failed', size: originalSize }
}

async function main() {
  if (!fs.existsSync(SOURCE_DIR)) {
    console.error(`错误：源目录不存在 "${SOURCE_DIR}"`)
    console.log('用法: node scripts/compress-photos.js [源目录]')
    console.log('或设置环境变量: PHOTOS_SOURCE=/your/photos/dir node scripts/compress-photos.js')
    process.exit(1)
  }

  if (!fs.existsSync(TARGET_DIR)) fs.mkdirSync(TARGET_DIR, { recursive: true })

  const exts = ['.jpg', '.jpeg', '.png', '.webp', '.gif']
  const files = fs.readdirSync(SOURCE_DIR).filter(f =>
    exts.includes(path.extname(f).toLowerCase())
  )

  console.log(`源目录: ${SOURCE_DIR}`)
  console.log(`找到 ${files.length} 张图片\n`)

  const results = []
  for (const file of files) {
    // 统一输出扩展名为处理后实际使用的扩展名
    let outName = file
    if (outName.toLowerCase().endsWith('.jpeg')) outName = outName.slice(0, -4) + 'jpg'

    process.stdout.write(`${file} → ${outName}... `)
    const result = await compressImage(
      path.join(SOURCE_DIR, file),
      path.join(TARGET_DIR, outName)
    )
    console.log(
      result.status === 'compressed'
        ? `${(result.size / 1024).toFixed(0)}KB`
        : result.status
    )
    results.push(result)
  }

  const succeeded = results.filter(r => r.status !== 'failed')

  // 生成 photos.js（按文件名排序）
  succeeded.sort((a, b) => a.name.localeCompare(b.name))

  const photosJs = `// Generated by compress-photos.js

export const photos = [
${succeeded.map(r => `  '${r.name}',`).join('\n')}
]
`
  fs.writeFileSync(path.join(__dirname, '../src/photos.js'), photosJs)

  console.log(`\n完成: ${succeeded.length}/${files.length} 张照片, ${results.filter(r => r.status === 'compressed').length} 张已压缩`)
}

main().catch(console.error)
