import sharp from 'sharp'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const SOURCE_DIR = 'D:/Web Documents/MY'
const TARGET_DIR = path.join(__dirname, '../public/photos')

const MAX_SIZE = 1024 * 1024 // 1MB

async function compressImage(inputPath, outputPath) {
  const stats = fs.statSync(inputPath)
  const originalSize = stats.size

  if (originalSize <= MAX_SIZE) {
    fs.copyFileSync(inputPath, outputPath)
    return { name: path.basename(outputPath), status: 'skipped', size: originalSize }
  }

  const formats = [
    { ext: 'jpg', quality: 85 },
    { ext: 'jpg', quality: 70 },
    { ext: 'jpg', quality: 50 },
    { ext: 'webp', quality: 85 },
    { ext: 'webp', quality: 70 },
  ]

  let bestFile = null
  let bestSize = originalSize

  for (const fmt of formats) {
    const tempPath = outputPath.replace(/\.[^.]+$/, '.' + fmt.ext)
    try {
      await sharp(inputPath)
        .resize(1920, 1920, { fit: 'inside', withoutEnlargement: true })
        [fmt.ext === 'jpg' ? 'jpeg' : fmt.ext](fmt.quality)
        .toFile(tempPath)

      const size = fs.statSync(tempPath).size
      if (size <= MAX_SIZE) {
        fs.renameSync(tempPath, outputPath)
        return { name: path.basename(outputPath), status: 'compressed', size }
      }
      if (size < bestSize) {
        bestSize = size
        bestFile = tempPath
      } else {
        fs.unlinkSync(tempPath)
      }
    } catch (e) {
      if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath)
    }
  }

  if (bestFile) {
    fs.renameSync(bestFile, outputPath)
    return { name: path.basename(outputPath), status: 'compressed', size: fs.statSync(outputPath).size }
  }

  return { name: path.basename(outputPath), status: 'failed', size: originalSize }
}

async function main() {
  if (!fs.existsSync(TARGET_DIR)) fs.mkdirSync(TARGET_DIR, { recursive: true })

  const exts = ['.jpg', '.jpeg', '.png', '.webp', '.gif']
  const files = fs.readdirSync(SOURCE_DIR).filter(f => exts.includes(path.extname(f).toLowerCase()))

  console.log(`Found ${files.length} images\n`)

  const results = []
  for (const file of files) {
    let outName = file
    if (outName.toLowerCase().endsWith('.jpeg')) outName = outName.slice(0, -4) + 'jpg'

    process.stdout.write(`${file} → ${outName}... `)
    const result = await compressImage(path.join(SOURCE_DIR, file), path.join(TARGET_DIR, outName))
    console.log(result.status === 'compressed' ? `${(result.size / 1024).toFixed(0)}KB` : result.status)
    results.push(result)
  }

  const succeeded = results.filter(r => r.status !== 'failed')
  fs.writeFileSync(path.join(__dirname, '../src/photos.js'), `// Generated by compress-photos.js

export const photos = [
${succeeded.map(r => `  '${r.name}',`).join('\n')}
]
`)

  console.log(`\nDone: ${succeeded.length}/${files.length} photos, ${results.filter(r => r.status === 'compressed').length} compressed`)
}

main().catch(console.error)